[project]
name = "kds-team-ex-heureka"
version = "0.0.0"
requires-python = ">=3.13"
dependencies = [
    "keboola.component==1.4.4",
    "keboola.utils==1.1.0",
    "keboola.csvwriter==1.0.1",
    "pydantic>=2.0",
    "backoff==2.2.1",
    "requests>=2.31.0",
]

[dependency-groups]
dev = [
    "mock==5.1.0",
    "freezegun>=1.4.0",
    "ruff",
    "pytest",
]

[tool.ruff]
line-length = 120
exclude = ["__pycache__", ".git", ".venv", "venv", "docs"]
